version: '3.8'

services:
  api:
    restart: on-failure
    build: .
    image: kawaiimelnik/spa_app
    env_file:
      .env
    ports:
      - "3061:3080"
      - "3071:3090"
    expose:
      - 3061
      - 3071
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:alpine
    restart: on-failure
    env_file:
      .env
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
volumes:
  postgres: