version: '3.8'

services:
  api:
    restart: on-failure
    build: .
    image: kawaiimelnik/spa_app
    env_file:
      .env
    ports:
      - "3080:3061"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - /spa_app/files:/app/files
    command: npm run start:dev

  migrations:
    image: kawaiimelnik/spa_app
    env_file:
      .env
    depends_on:
      - postgres
    command: npm run migration:run

#    command: bash -c "npm run migration:generate -d ./db/migrations/migration && npm run migration:run"


  postgres:
    image: postgres:alpine
    restart: on-failure
    env_file:
      .env
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
#      - ./init:/docker-entrypoint-initdb.d
volumes:
  postgres: