version: '3.8'

services:
  api:
    image: kawaiimelnik/spa_app
    env_file:
      .env
    ports:
      - 3333:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      .env