version: '3.8'

services:
  api:
    restart: on-failure
    build: .
    image: kawaiimelnik/spa_app
    env_file:
      .env
    ports:
      - "3080:3061"
    depends_on:
      - postgres
    volumes:
      - /spa_app/files:/app/files
    command: npm run start:prod

  migrations:
    image: kawaiimelnik/spa_app
    env_file:
      .env
    depends_on:
      - postgres
    command: npm run migration:run

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    env_file:
      .env
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: